src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse mail est déjà utilisée.')]
#[UniqueEntity(fields: ['pseudonym'], message: 'Ce pseudonyme est déjà utilisé.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 40)]
    private ?string $pseudonym = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $registrationDate = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $photo = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Publication::class)]
    private Collection $publications;

    #[ORM\Column]
    private ?bool $is_verified = false;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $resetToken = null;

    public function __construct()
    {
        $this->publications = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudonym(): ?string
    {
        return $this->pseudonym;
    }

    public function setPseudonym(string $pseudonym): self
    {
        $this->pseudonym = $pseudonym;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registrationDate;
    }

    public function setRegistrationDate(\DateTimeInterface $registrationDate): self
    {
        $this->registrationDate = $registrationDate;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Publication>
     */
    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): self
    {
        if (!$this->publications->contains($publication)) {
            $this->publications->add($publication);
            $publication->setAuthor($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): self
    {
        if ($this->publications->removeElement($publication)) {
            // set the owning side to null (unless already changed)
            if ($publication->getAuthor() === $this) {
                $publication->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

}

templates/base.html.twig
{# Variable twig "route" pour contenir le nom de la route chargée (classe active du menu) #}
{% set route = app.request.attributes.get('_route') %}

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">

    {# Balise meta description #}
    <meta name="description" content="Site du Rugby Club du Pays Graylois, pour découvrir l'association, vous informer ou prendre contact avec le club !">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {# Affichage du titre de page suivi du nom du site #}
    <title>{% block title %}{% endblock %} - {{ site_name }}</title>

    {# Lien cdn Google fonts #}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin">

    {# Lien cdn font-Awesome #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

    {# Inclusion css Bootstrap #}
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">

    {# Inclusion css perso #}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">

    {# Block pour le css additionnel #}
    {% block css %}{% endblock %}

</head>
<body>

    {# Inclusion dans un block du menu principal afin de pouvoir changer la configuration de ce dernier #}
    {% block navbar %}{% include 'partials/_main_navbar.html.twig' %}{% endblock %}

    {# Condition d'affichage des messages relatifes à la vérification du compte #}
    {% if app.user and app.user.isVerified == false %}
        <div class="alert alert-warning alert-dismissible col-12 col-md-10 mt-5 alert text-center mx-auto" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                <div class="alert-message">
                    <strong>Votre compte n'est pas activé.</strong>
                    <a href="{{ path('resend_verif') }}" class="text-dark">Renvoyer un lien d'activation.</a>
                </div>
        </div>
    {% endif %}

    {# Inclusion des messages flash #}
    {% include 'partials/_flashes.html.twig' %}

    {# Block pour le contenu des pages #}
    {% block body %}{% endblock %}

    {# Block pour le footer #}
    {% block footer %}{% include 'partials/_footer.html.twig' %}{% endblock %}

    {# inclusion js Bootstrap #}
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>

    {# Block pour le js additionnel #}
    {% block js %}{% endblock %}

</body>
</html>